# action.yml
name: 'Arch Linux Builder Action'
description: 'Build packages and more'
inputs:
  action:
    description: 'What to build. Valid options: build-package, build-repo, build-aur, run-custom'
    required: true
    default: 'build-package'
  target:
    description: 'Target to build. For `build-package`, this is a directory containing a `PKGBUILD`, for `build-aur` these are package names to be fetched from AUR, for `build-repo`, this is a directory containing package files, for `run-custom`, this is a path to a custom build script.'
    required: true
    default: '.'
  artifacts:
    description: 'Output artifacts are placed here. For `build-repo` this is the database name.'
    required: true
    default: 'output'
  packager:
    description: 'For build-package: Specify the packager name'
    required: false
    default: "GitHub Actions Packager"
  gpgsign:
    description: 'GPG Key to use for signing packages or repository files'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/archlinux-ostree-experiments/builder:latest'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.target }}
    - ${{ inputs.artifacts }}
    - ${{ inputs.gpgsign }}
    - ${{ inputs.packager }}
branding:
  icon: 'loader'
  color: 'blue'
